import fs from "node:fs";
import path from "node:path";

export function buildRegressionContract(root, framework, findings) {
  const routes = [];
  const apis = [];
  if (fs.existsSync(root)) {
    for (const f of walk(root)) {
      if (f.match(/app\/.*\/page\.(tsx|jsx)$/)) routes.push("/" + f.replace(/^app\//, "").replace(/\/page\.(tsx|jsx)$/, "").replace(/\/page$/, "") || "/");
      if (f.match(/app\/api\/.*\/route\.(ts|js)$/)) {
        const seg = f.replace(/^app\/api\//, "").replace(/\/route\.(ts|js)$/, "");
        apis.push(`/api/${seg}`);
      }
      if (f.match(/pages\/api\/.*\.(ts|js)$/)) {
        apis.push("/" + f.replace(/^pages/, "").replace(/\.(ts|js)$/, ""));
      }
    }
  }

  const pkg = readJson(path.join(root, "package.json"));
  const buildCmd = pkg?.scripts?.build ? "npm run build" : "npm run build";
  const testCmd = pkg?.scripts?.test ? "npm run test" : null;

  const safeDeletes = findings.filter((f) => f.action === "SAFE_DELETE");

  return {
    title: "Regression Contract",
    must_pass: {
      build_command: buildCmd,
      test_command: testCmd,
      routes_to_load: [...new Set(routes)].slice(0, 20),
      api_endpoints: [...new Set(apis)].slice(0, 20),
      auth_pages: routes.filter((r) => /login|auth|signup/i.test(r)),
    },
    manual_qa: [
      "Homepage loads without 500",
      "Primary navigation links work",
      "Auth flow completes (if applicable)",
      "API health endpoint returns 200",
      "No console errors on critical paths",
      "Build succeeds locally after patch",
    ],
    after_cleanup_verify: safeDeletes.map((f) => `Confirm removed: ${f.file_path || f.package} — ${f.reason}`),
    do_not_delete: findings.filter((f) => f.action === "DO_NOT_TOUCH").map((f) => f.file_path),
  };
}

export function regressionMarkdown(contract) {
  const lines = [
    "# Regression Contract",
    "",
    "Generated by RepoDiet. Verify these before merging any cleanup patch.",
    "",
    "## Build",
    "",
    "```bash",
    contract.must_pass.build_command,
    "```",
    "",
  ];
  if (contract.must_pass.test_command) {
    lines.push("## Test", "", "```bash", contract.must_pass.test_command, "```", "");
  }
  lines.push("## Routes that must load", "");
  for (const r of contract.must_pass.routes_to_load) lines.push(`- [ ] ${r || "/"}`);
  lines.push("", "## API endpoints", "");
  for (const a of contract.must_pass.api_endpoints) lines.push(`- [ ] ${a}`);
  lines.push("", "## Manual QA", "");
  for (const q of contract.manual_qa) lines.push(`- [ ] ${q}`);
  lines.push("", "## Post-cleanup checks", "");
  for (const c of contract.after_cleanup_verify.slice(0, 30)) lines.push(`- [ ] ${c}`);
  return lines.join("\n");
}

export function cursorPromptMd(scan, findings, contract) {
  const safe = findings.filter((f) => f.action === "SAFE_DELETE");
  const review = findings.filter((f) => f.action === "REVIEW_FIRST");
  return `# RepoDiet Cursor Cleanup Prompt

Apply this cleanup to the repository **${scan.repo_url || "local"}** (${scan.framework}).

## Rules
- Only delete SAFE_DELETE items without asking.
- REVIEW_FIRST items need human confirmation before removal.
- Run \`${contract.must_pass.build_command}\` after every batch of deletes.
- Do not touch DO_NOT_TOUCH paths.

## SAFE DELETE (${safe.length})
${safe.map((f) => `- ${f.file_path}${f.package ? ` (pkg: ${f.package})` : ""}: ${f.reason}`).join("\n")}

## REVIEW FIRST (${review.length})
${review.slice(0, 25).map((f) => `- ${f.file_path}: ${f.reason}`).join("\n")}

## Regression contract
${contract.manual_qa.map((q) => `- ${q}`).join("\n")}

After cleanup, re-run RepoDiet scan and confirm bloat score dropped from ${scan.summary?.bloat_score_before ?? scan.summary?.bloat_score} to a lower value.
`;
}

export function reportMarkdown(scan, findings) {
  const s = scan.summary;
  return `# RepoDiet Report

**Repo:** ${scan.repo_url || "demo"}  
**Framework:** ${scan.framework}  
**Bloat score:** ${s.bloat_score}/100  
**Scan mode:** ${scan.mode}

## AI Slop Fingerprint
- Duplicate clusters: ${s.duplicate_clusters}
- Unused files: ${s.unused_files}
- Unused dependencies: ${s.unused_dependencies}
- Orphan routes: ${s.orphan_routes}
- AI slop pattern hits: ${s.ai_slop_hits}
- Review required: ${s.review_required}

## Delete Confidence Engine
| Action | Count |
|--------|-------|
| SAFE DELETE | ${s.safe_deletes} |
| REVIEW FIRST | ${s.review_required} |
| DO NOT TOUCH | ${findings.filter((f) => f.action === "DO_NOT_TOUCH").length} |

## Top findings
${findings
  .slice(0, 40)
  .map((f) => `- **${f.action}** \`${f.file_path}\` — ${f.reason}`)
  .join("\n")}
`;
}

export function generatePatch(findings, root) {
  const lines = ["# RepoDiet cleanup.patch", "# Safe-delete operations — apply with git apply or manual review", ""];
  const safe = findings.filter((f) => f.action === "SAFE_DELETE");

  for (const f of safe) {
    if (f.type === "unused_dependency" && f.package) {
      lines.push(`# REMOVE dependency: ${f.package}`);
      lines.push(`--- a/package.json`);
      lines.push(`+++ b/package.json`);
      lines.push(`@@ remove unused dependency ${f.package}`);
      lines.push("");
      continue;
    }
    if (f.type === "dead_file" && f.file_path && f.file_path !== "package.json") {
      const abs = path.join(root, f.file_path);
      if (fs.existsSync(abs)) {
        lines.push(`diff --git a/${f.file_path} b/${f.file_path}`);
        lines.push(`deleted file mode 100644`);
        lines.push(`--- a/${f.file_path}`);
        lines.push(`+++ /dev/null`);
        const content = fs.readFileSync(abs, "utf8").split("\n");
        lines.push(`@@ -1,${content.length} +0,0 @@`);
        for (const line of content.slice(0, 50)) {
          lines.push(`-${line}`);
        }
        if (content.length > 50) lines.push(`# ... truncated (${content.length} lines total)`);
        lines.push("");
      }
    }
  }

  if (lines.length <= 4) {
    lines.push("# No automatic safe deletes — review REVIEW_FIRST findings manually.");
  }
  return lines.join("\n");
}

export function beforeAfterDelta(before, after) {
  return {
    bloat_score: { before: before.bloat_score, after: after.bloat_score, delta: before.bloat_score - after.bloat_score },
    unused_files: { before: before.unused_files, after: after.unused_files },
    unused_dependencies: { before: before.unused_dependencies, after: after.unused_dependencies },
    duplicate_clusters: { before: before.duplicate_clusters, after: after.duplicate_clusters },
  };
}

function walk(root, rel = "") {
  const out = [];
  if (!fs.existsSync(root)) return out;
  for (const ent of fs.readdirSync(root, { withFileTypes: true })) {
    if (["node_modules", ".git", ".next"].includes(ent.name)) continue;
    const relPath = rel ? `${rel}/${ent.name}` : ent.name;
    const abs = path.join(root, relPath);
    if (ent.isDirectory()) out.push(...walk(abs, relPath));
    else out.push(relPath);
  }
  return out;
}

function readJson(p) {
  try {
    return JSON.parse(fs.readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}
